services:
  app:
    entrypoint:
    - /.vscode/installExtensions.sh
    # - sleep
    # - infinity
    # build:
    #   dockerfile: Dockerfile
    image: antonlage/espimage:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

