services:
  app:
    entrypoint:
    - sleep
    - infinity
    iamge: ubuntu:22.04
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

